### ISSUE TITLE
architecture design enhancement

### ISSUE THREAD

**Issue by jjhesk** [wcandillon/react-native-img-cache#11]
i have a question. Can I can an notification when the all the images are cached hit in the local storage? 

assume i have

images = [
uri1, uri2, uri3, ...
]
should be better when all of these paths are cached successfully and have the final notification. Can I also have the size dimension of each image in return automatically?

**Comment by wcandillon** [comment]
@jjhesk Did you look at the `on()` method: https://github.com/wcandillon/react-native-img-cache#onuri-observer-immutable? When notified, you can use [Image.getSize()](https://facebook.github.io/react-native/docs/image.html#getsize) to get the size of the image. Does this fit your requirements?

**Comment by wcandillon** [comment]
@jjhesk I'm closing this issue for now, feel free to re-open.
