### ISSUE TITLE
Android still cannot read file from cache.

### ISSUE THREAD

**Issue by zobeirhamid** [wcandillon/react-native-img-cache#24]
Hello!
I tried using CachedImage but it won't show the image. It shows the Image tag, but with a blank view. I checked whether the file exists, and it exists (checked in the avd shell and also with fs.exists). 
It works perfectly with iOS. If I use fileCache instead of path it works without problems.

Maybe it is because of the Firebase Storage, that the link has some end to it. "http://firebase..../2F5F4SaNi6oPe0gW6MXvyU4jC0LPq1%2F49s3efwPUGRT8lB9RTRBYyy8Lpm2%2F1489646918723.jpg?alt=media&token=08e6fe22-9a8c-4455-9b8a-ca4b10828a0b"

-----
The problem was the URL, you need a clean filename like 'esgeahr25awrga.jpg'

**Comment by JimmyDaddy** [comment]
hello, I still have this problem , did you fix it?

**Comment by wcandillon** [comment]
@zobeirhamid @JimmyDaddy This is fixed in `1.1.10`. Sorry about that and thank you for reporting it.
