### ISSUE TITLE
when I want to clear cache by bust function, but the cache show more picture

### ISSUE THREAD

**Issue by firstBird-1** [wcandillon/react-native-img-cache#30]
I want to clear the picture in cache, but show double number of picture in the cache .seens like copyed again the source in the path

**Comment by wcandillon** [comment]
@firstBird-1 bust only re-downloads the image for the cache entry. It doesn't remove any files. Were you expecting a different behaviour?

**Comment by firstBird-1** [comment]
So there is any function to clear cache or remove the image from cache?

**Comment by firstBird-1** [comment]
@wcandillon I see the explain "The lifetime of this cache is the one of the running application".If I turn off the App, the Cache will be done with all the image deleted?

**Comment by wcandillon** [comment]
@firstBird-1 Not at the moment because I find this feature orthogonal. Image are stored in the iOS/Android cache folder and they have a lifecycle on their own.

@firstBird-1 yes for images cached with the `mutable` attribute.

**Comment by firstBird-1** [comment]
@wcandillon Thanx~~

**Comment by wcandillon** [comment]
@firstBird-1 you're welcome, feel free to reopen if you have more questions.
