### ISSUE TITLE
ImageCache.get() is throwing an error

### ISSUE THREAD

**Issue by jbrunson** [wcandillon/react-native-img-cache#35]
I have been trying to clear the cached entries and physical files but getting an error. Recently when I call ImageCache.get() or ImageCache.get().clear() I get this error... (_reactNativeImgCache.ImageCache.get is not a function).  It looks like some recent updates may have broken this behavior but any advice would be greatly appreciated.

**Comment by wcandillon** [comment]
@jbrunson Is it possible that you are not using the latest version of the package? `get()` was introduced in version `1.2.0`. Which version are you using?

**Comment by jbrunson** [comment]
That was it....I was using an older version for some reason. Thank you!!

**Comment by wcandillon** [comment]
@jbrunson 👍
