### ISSUE TITLE
Progress indicator on downloading 

### ISSUE THREAD

**Issue by maxim-kolesnikov** [wcandillon/react-native-img-cache#36]
How can I get the image upload process?
or
Could you add props progress indicator if image download?
as like ```indicator={`Platform.OS === 'ios' ? Circle : Pie`}```

**Comment by wcandillon** [comment]
@mxklsn Your use case should be supported once #37 is merged.

**Comment by wcandillon** [comment]
@mxklsn Please feel feed to re-open this issue if you have any problem with this new version.
