### ISSUE TITLE
Question: Difference between this library and native cache property

### ISSUE THREAD

**Issue by clemmy** [wcandillon/react-native-img-cache#39]
https://facebook.github.io/react-native/docs/image.html

Hi there! I was just wondering if there is a difference between this library and specifying `cache: 'only-if-cached'` on an `<Image/>` component.

**Comment by wcandillon** [comment]
@clemmy, the cache attribute didn't exist at the time I wrote the package. I will try to use it and see if I can get the same UX quality than with `react-native-img-cache` and let you know. Thank you for pointing that out.

**Comment by wcandillon** [comment]
@clemmy I added a comment in the README, let me know if it makes sense or not.

**Comment by clemmy** [comment]
Thanks :)
