### ISSUE TITLE
The latest version 1.3.1 cannot run on RN 0.42

### ISSUE THREAD

**Issue by gameboyVito** [wcandillon/react-native-img-cache#47]
Hi, thanks for your awesome module. I am currently using react-native v0.42.3. After I updated to react-native-img-cache v1.3.1, it encountered error, but v1.3.0 is perfect for react-native < 0.43. Please noted and if you can tag your release version, that would be nice. ^_^

**Comment by wcandillon** [comment]
Thanks for reporting this. Which error did you get?

**Comment by gameboyVito** [comment]
After I upgraded to react-native 0.44.0 and react 16.0.0-alpha.6, I still got the same error. It said: `Error: uri property missing ImageURISource parameter`. However, when I used react-native-img-cache 1.3.0, everything worked correctly, but 1.3.1 always shows that error.

**Comment by wcandillon** [comment]
@gameboyVito This error seems to indicate that you are trying to cache a local image. Is there a use case for it? It sounds similar to #50 but I am not sure what is the use case for it. Could you elaborate?

**Comment by wcandillon** [comment]
@gameboyVito This is fixed in `1.4.0`. Please let me know if you have more issues.

**Comment by gameboyVito** [comment]
It works! Thank you so much. @wcandillon
