### ISSUE TITLE
Cannot show Pictures after certain number of pics on Android

### ISSUE THREAD

**Issue by kingpeterson** [wcandillon/react-native-img-cache#49]
This is my environment: 
React-native 0.43.4
React-native-img-cache 1.3.0
Android 6.0 +

As shown in the screenshots below, after certain numbers of pics, it just shows blank, rather than the picture itself. 
I can confirm that the pics have been successfully saved in the cache. This problem only occurs in Android, it works fine in iOS devices.
Please help me solve this issue, thank you!
 
![0-ea-d1-bf030ed18c46286e09d375be8b96c8ed](https://cloud.githubusercontent.com/assets/10936258/25645733/d875aeac-2fe3-11e7-826b-d790268959aa.jpg)

![0-ea-d2-696666538740c8c7c74cb64d84d40853](https://cloud.githubusercontent.com/assets/10936258/25645738/e2d71bb0-2fe3-11e7-9259-5ffc609e0380.jpg)

![0-ea-d1-2404a4be4fafa3a332086e1f37eecaa6](https://cloud.githubusercontent.com/assets/10936258/25645740/e637fbb2-2fe3-11e7-8965-2f1087b786e9.jpg)

**Comment by wcandillon** [comment]
@kingpeterson I'm sorry that you are experiencing this issue. Unfortunately, I wasn't able to reproduce it in my own project. Do you have an example project I could look at in order to reproduce the issue? Or just send me some sample component that could allow me to reproduce the issue quickly.

**Comment by dotansimha** [comment]
@kingpeterson , does your pictures are PNG?

**Comment by kingpeterson** [comment]
I resolved the issue..
Had to add  android:largeHeap="true" to AndroidManifest.xml
