### ISSUE TITLE
Need support require from local

### ISSUE THREAD

**Issue by hungdev** [wcandillon/react-native-img-cache#50]
thank for lib, but it still run uri image link, dont run with require source.
i hope lib support require: source={require('../Images/no-avatar.png')}

**Comment by wcandillon** [comment]
@hungdev Images like `require('../Images/no-avatar.png')` are bundled within the javascript. What would be your use case to use such images via `react-native-img-cache`?

**Comment by hungdev** [comment]
@wcandillon  i want to use react-native-img-cache like this:
```
                      <CachedImage
                        resizeMode='cover'
                        indicatorProps={{ color: '#fff' }}
                        source={require('../Images/no-avatar.png')}
                        style={styles.imageSelected}
                      />
```

**Comment by wcandillon** [comment]
@hungdev I'm not sure why you would want to cache a local image. Should you only need to cache remote images?

**Comment by dotansimha** [comment]
@wcandillon I have a similar use case. 
I have an Image component, that it's source could be from remote server, or a default image from assets, but I want the view to be the same.

**Comment by wcandillon** [comment]
@hungdev @dotansimha This is fixed in `1.4.0`. Please let me know if you have more issues.

**Comment by hungdev** [comment]
@wcandillon , thank you so much.

**Comment by dotansimha** [comment]
Thanks @wcandillon !
