### ISSUE TITLE
How to get image size from cache ?

### ISSUE THREAD

**Issue by ldubos** [wcandillon/react-native-img-cache#70]
Hi !

I need to know the size of an image to resize it by width and preserve ratio.
I've tried to use **react-native-auto-height-image**, but it doesn't support `source` prop,
the displayed image it gets from cache and the size from URL... It's not the behavior that I expect.

So, How can I get image size from cache with **react-native-img-cache** ?

thank you in advance 😃

**Comment by antondomratchev** [comment]
@ldubos, you can simply use `getSize()` method on the Image component https://facebook.github.io/react-native/docs/image.html#methods to get the width and height of an image. However, if you are trying to get the size of an image already in cache you will need to get a path of the image in cache using the `ImageCache` `on` method https://github.com/wcandillon/react-native-img-cache#onuri-observer-immutable.

**Comment by ldubos** [comment]
Ok thanks

**Comment by nes123** [comment]
How to turn off the ImageCache.get.on()

I am trying to do it with the dispose but it does not work
