### ISSUE TITLE
ReactNative ImageBackground

### ISSUE THREAD

**Issue by shahankit** [wcandillon/react-native-img-cache#71]
As of ReactNative 0.46 using, it's recommended to use `ImageBackground` component whenever `Image` has children. This is possible using `CustomImageCache` component as follow:

```jsx
<CustomCachedImage
    component={ImageBackground}
    source={{ uri: 'http://loremflickr.com/640/480/dog' }} 
/>
```

Although if there is a directly available component name CachedImageBackground to import then it would be great.

**Comment by wcandillon** [comment]
I didn't know about `ImageBackground`, indeed this would be a good idea.

**Comment by wcandillon** [comment]
@shahankit Can you point me to the documentation of `ImageBackground ` ?

**Comment by shahankit** [comment]
I get a console warning whenever using `<Image />` with children to use `<ImageBackground />` instead. I found this in documentation for `ImageBackground`: http://facebook.github.io/react-native/releases/0.48/docs/images.html#background-image-via-nesting

**Comment by wcandillon** [comment]
Thks a lot 👍🏻

**Comment by gameboyVito** [comment]
Same issue. Please fix it, thanks.

**Comment by brianhiss** [comment]
@wcandillon I'm getting a depreciated message in `react-native 0.49.2`.

`Using <Image> with children is deprecated and will be an error in the near future.`

Looks like their going to depreciate in the next release or two.

**Comment by jayshah123** [comment]
looks like you have landed a fix in master, If it is usable, would you be willing to cut a release?

**Comment by wcandillon** [comment]
@jayshah123 Thank you for pointing that out, will make a release now.
