### ISSUE TITLE
DocumentDir of undefined.

### ISSUE THREAD

**Issue by jjhesk** [wcandillon/react-native-img-cache#8]
not working..
DocumentDir of undefined.
RN 0.41.2
"react-native-fetch-blob": "^0.10.2",

**Comment by wcandillon** [comment]
@jjhesk where do you see `DocumentDir` being used?

**Comment by jjhesk** [comment]
@wcandillon  it is fixed by correctly linking the fetch-blog to the compiler.

**Comment by wcandillon** [comment]
great thks!

**Comment by charlesfayal** [comment]
@jjhesk how did you correctly link the fetch-blog?
I installed it with npm install --save 
then linked with react-native link
