### ISSUE TITLE
Local image support broken in 1.5.x

### ISSUE THREAD

**Issue by richeterre** [wcandillon/react-native-img-cache#86]
I noticed that support for local images, which had been added by https://github.com/wcandillon/react-native-img-cache/pull/51, is broken in newer versions starting from NPM release 1.5.0. On those versions, the library again throws an error when passing a `source` of type `number` to the `CachedImage` component.

Apparently the error-throwing source check was re-introduced by this commit: https://github.com/wcandillon/react-native-img-cache/commit/8d5c07333f3dfda548105f4829843d93a4de5f55#comments

Was this on purpose or by accident? Unfortunately I couldn't find any changelog or release notes that would explain how different versions are intended to behave.

**Comment by wcandillon** [comment]
@richeterre Indeed it was regression with the typing, should be fixed in `1.5.3`. Feel free to reopen if this is not the case.

**Comment by richeterre** [comment]
Thank you, works great! 👌
