### ISSUE TITLE
ImageCache.get().clear() is not working on CustomCachedImage

### ISSUE THREAD

**Issue by pavinthan** [wcandillon/react-native-img-cache#89]
CustomCachedImage always show first user image
Image url like `{DOMAIN_NAME}/api/profile/images/cropped` 

```
<CustomCachedImage
     component={Thumbnail}
     large
     source={{
     uri: profileImage(),
     headers: {
        Authorization: oauth.token_type + ' ' + oauth.access_token
     },
}}/>
```

```
ImageCache.get().clear().done(() => {
    // some code
});
```

**Comment by aalkhulaifi605** [comment]
I am having the same issue where if the user updated his image on the backend , the app won't load the new image and will always load from cache . Setting it to mutable will fix this issue but the image will not be displayed when the user is offline and the app will always request the image .

Does the lib auto delete cache after their max-age is expiated ? My backend does return cache control with max-age but not sure if the lib will auto delete .

**Comment by mayur-padshala** [comment]
To your image URI, try adding the user id in query parameter. 
Example: ```uri: `${profileImage()}?userId=${user_id}`,```

This will make the URLs unique to each user and would help resolve your issue.

**Comment by pavinthan** [comment]
@Nitroman605 @mayur-novus thanks for your advice, I used  `/api/profile/images/cropped?uuid={UUID}` to fix the issue.

Thanks again.
